name: COPY SOURCE FILES
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EngineRepo: https://github.com/miscdec/flutter_engine.git
      EngineBranch: master
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
      - name: Get python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install packages
        run: sudo apt-get install -y git wget curl software-properties-common unzip python-pip lsb-release sudo apt-transport-https ninja-build
      - name: Clone depot_tools
        run: git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Clone Flutter repo
        run: | 
          git clone --depth 1 -b $EngineBranch --single-branch $EngineRepo
      - name: gcclient Setup
        run: |
           ROOT_DIR=`pwd` 
           export PATH=$ROOT_DIR/depot_tools:$PATH
           mkdir customEngine
           cd customEngine
           echo 'solutions = [{"managed": False,"name": "src/flutter","url": "'$ROOT_DIR/engine'","custom_deps": {},"deps_file": "DEPS","safesync_url": "",},]' > .gclient
           gclient sync
      - name: Copy gcfiles
        run: |
         mkdir builds
         cp customEngine/src/third_party/dart/runtime/vm/clustered_snapshot.cc gclientcopy/clustered_snapshot.cc 2>/dev/null || :
         cp customEngine/src/third_party/dart/runtime/vm/class_table.cc gclientcopy/class_table.cc 2>/dev/null || :
         cp customEngine/src/third_party/dart/runtime/bin/socket.cc gclientcopy/socket.cc 2>/dev/null || :
      - name: Save the gcfiles files
        uses: actions/upload-artifact@v3
        with:
          name: sourceFiles
          path:  gclientcopy/*.cc
          if-no-files-found: warn
